//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cursed.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerComponentRelationship
    {
        public int PC_Comp_RelationId { get; set; }
        public int ComputerId { get; set; }
        public int ComponentId { get; set; }
    
        public virtual Components Components { get; set; }
        public virtual Computers Computers { get; set; }
    }
}
